export {BackgroundTopImage} from './BackgroundTopImage/BackgroundTopImage'
export {SecondComp} from './SecCom/SecondComp'
export {ThreeBoxes} from './ThreeBoxes/ThreeBoxes'
export {NFTLaunchpad} from './NFTLaunchpad/NFTLaunchpad'
export {NFTRewardPool} from './NFTRewardPool/NFTRewardPool'