export {BackgroundTopImage} from './BackgroundTopImage/BackgroundTopImage'
export {SecondComp} from './SecCom/SecondComp'
export {ThreeBoxes} from './ThreeBoxes/ThreeBoxes'
export {NFTLaunchpad} from './NFTLaunchpad/NFTLaunchpad'
export {NFTRewardPool} from './NFTRewardPool/NFTRewardPool'
export {G50DropLottery} from './G50DropLottery/G50DropLottery'
export {Tokenomics} from './Tokenomics/Tokenomics'