# This is a basic workflow to help you get started with Actions

name: React App deploy to surge 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Installs Node JS
    - name: Insatlling Nodejs
        uses: actions/setup-node@v2-beta
        with:
           version: 14
       
      - name: Installing yarn
        uses: Borales/actions-yarn@v2.1.0
        with: 
           cmd: install
           
      - name: yarn build
        run: sudo yarn build
      # Runs a set of commands using the runners shell
      - name: Installing Surge
        run: npm install -g surge
      - name: Deploying on Surge
      run: surge ./build 8020_testing.surge.sh --token ${{ secrets.SURGE_TOKEN }}
